# Functions
---

Python Functions is a block of related statements designed to perform a computational, logical, or evaluative task. The idea is to put some commonly or repeatedly done tasks together and make a function so that instead of writing the same code again and again for different inputs, we can do the function calls to reuse code contained in it over and over again. 

Functions can be both built-in or user-defined. It helps the program to be concise, non-repetitive, and organized.

### Syntax

Function definition

The function definition starts with a def keyword followed by the function name and the arguments the function can take. These arguments are within parentheses and there can be any number of arguments including zero. When there is more than one argument, they are separated by a comma. Since python is a loosely typed language, (meaning we don’t assign a data type to a variable when declaration) we shouldn’t include the data types for the arguments. The function definition statement is terminated by a colon. In python, we define a function as follows:

### Creating a Function
We can create a  Python function using the def keyword.

In [7]:
def fun():# first we created function named fun
    print("Hello 'Deepanshu' ")

In [8]:
fun()

Hello 'Deepanshu' 


In [9]:
def add(a,b):
    print(a+b)
x=int(input('emter x '))
y=int(input('enter y '))
add(x,y)

emter x 4
enter y 4
8


In [17]:
fun()
# every time we call this fun function it will give same value

Hello 'Deepanshu' 


In [35]:
def deepanshu():
    print('python')
    print('Data science')

deepanshu()

python
Data science


In [36]:
def deepanshu():
    print('python')
    print('Data science')

deepanshu()
print('AI') # it is not a part of then function


python
Data science
AI


In [40]:
def add():
    a=int(input('enter a '))
    b=int(input('enter b '))
    result=a+b
    print('the addition of two variable is',result)
print('Befote function call')
add()

print('After function call ')

Befote function call
enter a 2
enter b 2
the addition of two variable is 4
After function call 


There are four ways to define function
- Takes Nothing,return Nothing
- Takes Something, return Nothing
- Takes Nothing, return Something
- Takes Someethong, return Something

In [41]:
# Takes Nothing return Nothing
def add():
    a=int(input('enter a '))
    b=int(input('enter b '))
    result=a+b
    print('the addition of two variable is',result)
   
add()


enter a 1
enter b 2
the addition of two variable is 3


In [42]:
s='deepanshu'
len(s)

9

In [11]:
c=0
def length(a):
    global c
    for i in  a:
        c+=1
    return(c)
# length('deepanshu')

In [6]:
# Takes Something, return Nothing
def add(M,N): # parameters or formal parameters
   
    
    result=M+N
    print('the addition of two variable is',result)
print('Please enter Two number')
a=int(input('enter number '))
b=int(input('enter number '))
add(a,b) # arguments or actual parameters


Please enter Two number
enter number 4
enter number 4
the addition of two variable is 8


In [13]:
# Takes Nothing return Something
def add():
    print('Please enter Two number')
    x=int(input('enter number '))
    y=int(input('enter number '))
    print(x+y)
    
    
    result=x+y

    return result

    
t=add()

# print('hii')



Please enter Two number
enter number 5
enter number 6
11


In [14]:
print(t)

11


In [17]:
# Takes something, return something
def add(x,y):
    print('hii')
    result=x+y
    
    return result
a=11
b=6


print(add(a,b))


hii
17


In [23]:
def hii():
    return 'yess'
    print('hey')
    print('hii')
   
    print('python')
    print('data abnalytics')
    
print('numpy')
z=hii()
print(z)
print('pandas')

numpy
yess
pandas


In [39]:
### when fuction returns nothing that time it returns none
def myfunc():
    print('hello')
   
rec=myfunc()
print(rec,'----',type(rec))

hello
None ---- <class 'NoneType'>


In [78]:
def D():
    print('hiii')
    print('hello')
    return 'python'
#     print('deepanshu')
    
#     print('verma')
    
# q=D()
# print(q)
D()
# print(S)

hiii
hello


'python'

In [26]:
def sub(R,S):
    print('hiii')
    print('1')
    result=R-S
   
    return result
    print('hello')
    print('2')
X=10
Y=20
k=sub(X,Y)
print(k)

hiii
1
-10


In [27]:
def tt():
    print('hii')
    return 'Deepanshu'
    print('hello')
K=tt()

hii


In [82]:
print(K)

Deepanshu


In [30]:
def anil(a,b,c):
    print(a+b+c)
    print('hii')
    return a+b+c
    print('yess')

deepanshu=anil(1,2,3)
print(deepanshu)

6
hii
6


In [97]:
def I(a,b):
    print(a+b)
    
m='hiii'
n='hello'
I(n,m)

hellohiii


When we call a function with some values, these values get assigned to the arguments according to their position.

Python allows functions to be called using keyword arguments.


When we call functions in this way, the order (position) of the arguments can be changed.


In [ ]:
def exam(p,q):
    print(p,q)

U='Hii'
T='Priyanka'
exam(U,T)

In [31]:
def student(firstname, lastname):
    print(firstname, lastname)
 
 
# Keyword arguments
# same as normal arguments but you can specify the argument 
# student(firstname='Madrid', lastname='Solutions')  
# student(lastname='Madrid', firstname='Solution')
a='Deepanshu'
b='Verma'
student(a,b)
# student(b,a)
# we gave same output but in diffrent order and still get same output 
# beacuse of keyword argument because we specified the arguments

Deepanshu Verma


#### The return statement
The function return statement is used to exit from a function and go back to the function caller and return the specified value or data item to the caller.

Syntax: return [expression_list]

The return statement can consist of a variable, an expression, or a constant which is returned to the end of the function execution. If none of the above is present with the return statement a None object is returned.

In [101]:

def square_value(num):
   
    return num**2
#     print('hiii')

    # ranther than printing result we can use return for getting value


# x=square_value(2)
# print(x)# it will return square of 2
square_value(-4)      # it will return square of -4

16

In [100]:

print(x)

4


In [59]:
5

5

In [102]:
def FUN(a,b):
    print('hiiii')
    return a+b
    return('Deepanshu')
    print('How are you ?')
    print('function funish')
C=10
G=20
print(FUN(10,20))


hiiii
30


In [63]:
def FUN(a,b):
    print('hiiii')
    return a+b
#     return('Deepanshu')
#     print('How are you ?')
#     print('function funish')
# C=10
# G=20
print(FUN(10,20))
print('yes')

hiiii
30
yes


In [103]:
# def without print or return
def lst(x):
    x[0] = 20
 
    print(x)

l = [10, 11, 12, 13, 14, 15]
lst(l)


[20, 11, 12, 13, 14, 15]


## Variable-length Arguments

You may need to process a function for more arguments than you specified while defining the function.

 These arguments are called variable-length arguments and are not named in the function definition, unlike required and default arguments.


In [ ]:
#Syntax:-

# def functionname([formal_args,] *var_args_tuple ):
#     function_suite 
#     return [expression]

#An asterisk (*) is placed before the variable name that holds the values of all non keyword variable arguments. 
#This tuple remains empty if no additional arguments are specified during the function call. 


In [104]:
def d(a,b,c):
    print(a,b,c)
    
x=int(input())
y=int(input())
z=int(input())

d(x,y,z)


2
3
6
2 3 6


In [32]:
def hlo(*args): # first we took argument as *args
    print(type(args),args)
    for arg in args: 
#         # since it is stored as tuple we need to use loop to acess the values 
        print(arg)
 
 
hlo(1,2,3,4,5,7,8,9,2)

<class 'tuple'> (1, 2, 3, 4, 5, 7, 8, 9, 2)
1
2
3
4
5
7
8
9
2


In [118]:
def find_average(*numbers):     
    print(numbers,type(numbers))
    
    print('average of all the numbers',sum(numbers)/len(numbers))
    
    
y=find_average(10,20,30,40,50,60,70,80,90,100,110,120,130)

(10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130) <class 'tuple'>
average of all the numbers 70.0


In [33]:
n=int(input('enter n '))
for i in range(n):
    def p(a):
        print(a**2)
        
    k=int(input('enter'))
    p(k)

enter n 3
enter10
100
enter2
4
enter3
9


In [1]:
def k(v):
    print(v)
for i in range(3):
    k(i)

0
1
2


In [2]:
a=(1,2,3,4)
print(*a)# Star is using for unpack

1 2 3 4


In [3]:
a={1:"a",2:"b"}
print(*a)

1 2


In [4]:
a={1:"a",2:"b"}
print(*a.values())

a b


In [5]:
a={1:"a",2:"b"}
print(*a.keys())

1 2


In [8]:
a={1:"a",2:"b"}
print(*a.items())

(1, 'a') (2, 'b')


In [10]:
a=[1,2,3,4]
print(*a)

1 2 3 4


In [11]:
a={1,2,3,4}
print(*a)

1 2 3 4


In [39]:
def printinfo(arg1,*vartuple):
   
    print("Output is:")
    print(arg1)
    print(vartuple)
    print(*vartuple)
    for var in vartuple:
        print(var)
    return var

printinfo(100,40,70,40)


Output is:
100
(40, 70, 40)
40 70 40
40
70
40


40

In [40]:
def printValue(arg1,*vartuple):
    print(arg1)
    print(*vartuple)
    print(vartuple)
    for v in vartuple:
        print(v)
# printValue(1)
printValue(1,2,3,4)
# printValue(1,2,"Three",4.0)


1
2 3 4
(2, 3, 4)
2
3
4


In [17]:
## Variable length arguments
def Average(*numbers):
    sum=0
    for num in numbers:
        sum+=num
    if len(numbers)!=0:
        print(sum)
        return sum/len(numbers)
    else:
        return "There is no numbers for avreage"


result=Average()
print(result)
result=Average(10,20,30,40,50)
print(result)



There is no numbers for avreage
150
30.0


In [47]:
def f1(teachername,batches,*points):
    print(teachername,batches)
#     print(points)
    s=0
    for x in points:
        s+=x
    print('Total points',s)

# f1('Deepanshu',10,11,12)
f1('Deepanshu',10,11,12,13,14,15)

Deepanshu 10
Total points 65


### This is the combination of variable length arguments and Keyword Arguments

In [48]:
def fun(**kwargs):                 # first we take argument as **kwargs 
    print(kwargs)
    for key in kwargs:
        print(key ,kwargs[key]) 
        print(kwargs[key])
        # since it is stored as dictionery we need to use loop 
        # to acess keys and values 

        
fun(a=1,b=2,c=3)

{'a': 1, 'b': 2, 'c': 3}
a 1
1
b 2
2
c 3
3


In [28]:
def game(**race):
    print(race)
    print(*race)
game(a=2,b=4,c=6,d=8)

{'a': 2, 'b': 4, 'c': 6, 'd': 8}
a b c d


In [29]:
def game(**race):
    print(race)
    print(*race)
    for i in race:
        print(i,race[i])
game(a=2,b=4,c=6,d=8)

{'a': 2, 'b': 4, 'c': 6, 'd': 8}
a b c d
a 2
b 4
c 6
d 8


In [32]:
x={'A':1}
print(x.items())
# print(x.values())
# print(x.keys())

dict_items([('A', 1)])


In [5]:
def faisal(a,b):
    print('hiii')
    print(a+b)
    
faisal(11,2)

hiii
13


In [49]:
def f2(**k):
    print(k)
    print(k.items())
    print('Person Information')
    for key,value in k.items():
        
        print(key,'--------',value)
        
f2(name='deepanshu',age=24,gender="Male")

{'name': 'deepanshu', 'age': 24, 'gender': 'Male'}
dict_items([('name', 'deepanshu'), ('age', 24), ('gender', 'Male')])
Person Information
name -------- deepanshu
age -------- 24
gender -------- Male


In [35]:
def x(*dash):
    print(dash)
    print("My name is" , dash[2])
    print("I'm a amazing " + dash[4])
    print("My " + dash[1]+ " is so good")
    print("I love to hear " + dash[5])
    print("My favorite food is "+ dash[0])
    print("I love " + dash[3]+ " life")
x("chicken","vibe","Robin","peacefull","guy","punjabi songs")



('chicken', 'vibe', 'Robin', 'peacefull', 'guy', 'punjabi songs')
My name is Robin
I'm a amazing guy
My vibe is so good
I love to hear punjabi songs
My favorite food is chicken
I love peacefull life


- you can use def function in single line 

In [36]:
def cube(x): return x**6

cube(7)

117649

- some examples of def function

In [51]:
def my_function(country = "Norway"):        
    print("I am from ",country)

my_function("Sweden")               
# # in a function that we have given the arugment it will work through that 
my_function("India")
my_function() 
# # in a function that we didn't give argument it will work through default argument
my_function("Brazil")

I am from  Sweden
I am from  India
I am from  Norway
I am from  Brazil


In [59]:
a=((1),3,(3,4),5)
# print(a[2:])
print(a[-1])
print(a[0:2]+a[2]+a[-1:])

5
(1, 3, 3, 4, 5)


In [18]:
def math():
    
    a = int(input('enter number '))
    b = int(input('enter number '))
    c = int(input('enter number '))
   
    g= a+b+c
    print('Additrion',g)
    d= a-b-c
    print('subtraction',d)
    e= a*b*c
    print('Multiplication',e)
    f=a/b/c
    print('Division',f)
    
math()


enter number 2
enter number 2
enter number 2
Additrion 6
subtraction -2
Multiplication 8
Division 0.5


## Scope of variables

All variables in a program may not be accessible at all locations in that program. This depends on where you have declared a variable.

The scope of a variable determines the portion of the program where you can access a particular identifier. 

There are two basic scopes of variables in Python
- Local variables
- Global variables


Local  vs. Global variables:-
    
    
Variables that are defined inside a function body have a local scope, and those defined outside have a global scope.

This means that local variables can be accessed only inside the function in which they are declared, whereas global variables can be accessed throughout the program body by all functions

In [60]:
x = 10

def function():
    print("Hello")
    
    YY= 20 # local variable
    print(YY)
    print(x)
    
    
function()
print(x)
print(YY) # YY is not print because YY variable is define inside the function.


Hello
20
10
10


NameError: name 'YY' is not defined

- Local scope variables can only be accessed within its block.

In [61]:
x = 10
def function():
    print("Hello")
    zz = 20
    print(zz)
function()
print(x)
print(zz)

Hello
20
10


NameError: name 'zz' is not defined

In [1]:
def add(a,b):
    return a+b
a=10
b=10
add(a,b)

20

In [62]:
# This demo is related with scope

total=0   # This is a global variable
def sum(a,b):
    total=a+b    # Here total is local variable
    print("The Sum of two number is ",total)

# Using Sum Func
sum(10,20)
print("The Total is ",total)# it is a gloabal variable



The Sum of two number is  30
The Total is  0


For example, we define a variable Money in the global namespace. Within the function Money, we assign Money a value, therefore Python assumes Money as a local variable. 


However, we accessed the value of the local variable Money before setting it, so an UnboundLocalError is the result. 
To overcome this problem we use the  global keyword

In [63]:
Money=1000
def Add_money():
    
    Money=Money+100 # we cant't modify the global variable inside the function
    print(Money)
    
print(Money)
Add_money()
print(Money)

1000


UnboundLocalError: local variable 'Money' referenced before assignment

In [65]:
Money=1000
def Add_money():
    a=Money
    a=a+100
    print(a)
    
print(Money)
Add_money()
print(Money+999)

1000
1100
1999


In [59]:
Money=2000 #global variable

def Add_Money():
    global Money  #global is used to acces the variable inside the function or to modify it
    Money=Money+1


print('the global variable before the function',Money)
Add_Money()
print('After assigning the global variable',Money)
print(Money)


the global variable before the function 2000
After assigning the global variable 2001
2001


In [60]:
# This function modifies global variable 's'
def f():
    global s
    print(s)
    s = "Madrid Software"
    print(s)

# Global Scope
s = "Welcome To !"
f()
print(s)


Welcome To !
Madrid Software
Madrid Software


In [3]:
# Python program to demonstrate
# scope of variable
a = 1
# Uses global because there is no local 'a'
def f():
    print('Inside f() : ', a)
# Variable 'a' is redefined as a local
def g():
    a = 2
    print('Inside g() : ', a)
# Uses global keyword to modify global 'a'
def h():
    
    global a
    a = 3
   
    print('Inside h() : ', a)

# Global scope
print('global : ', a)
f()
print('global : ', a)
g()
print('global : ', a)
h()
print('global : ', a)


global :  1
Inside f() :  1
global :  1
Inside g() :  2
global :  1
Inside h() :  3
global :  3


In [4]:
a=1
def h():
    global a
    a = 3
    print('Inside h() : ', a)
print(a)
h()

1
Inside h() :  3


In [12]:
add(100,300)

400


In [14]:
add(500.2,500.3)

1000.5


In [48]:
# length('sdfghjkjhgfdsdklkuytrtyu')

In [51]:
x='verma'
length(x)

14

In [135]:
import numpy as np
L=[]
i=int(input('emter i '))
j=int(input('enter j'))
size=i*j
for i in range(size):
    
    a=int(input('enter a '))
    L.append(a)
    
b=np.array((L),ndmin=2)
b.reshape((5,5))



emter i 5
enter j5
enter a 1
enter a 1
enter a 1
enter a 1
enter a 1
enter a 1
enter a 0
enter a 0
enter a 0
enter a 1
enter a 1
enter a 0
enter a 9
enter a 0
enter a 1
enter a 1
enter a 0
enter a 0
enter a 0
enter a 1
enter a 1
enter a 1
enter a 1
enter a 1
enter a 1


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [132]:
print(b)


[[0 0 0 0 0 0 1 2 3 4 0 2 4 6 8]]


array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [137]:
a=np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [140]:
b=np.zeros((3,3))
b[1][1]=9
print(b)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [141]:
a[1:4,1:4]=b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
def add(a,b):
    '''This is for addition'''
    c=a+b
    return c

In [7]:
x=add(2,4)
x

6

In [9]:
print(add.__doc__)

This is for addition
